In [1]:
import torch
x= torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
x.reshape(3, 4)
'''
tensor([[ 0, 1, 2, 3],
				[ 4, 5, 6, 7],
				[ 8, 9, 10, 11])'''


x.view(2, 6)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [4]:
import torch
a = torch.randn(3, 4)
a.transpose_(0, 1)
b = torch.randn(4, 3)

In [6]:
# a 텐서 메모리 주소 예시
for i in range(4) :
	for j in range(3) :
		print(a[i][j].data_ptr())

# b 텐서 메모리 주소 예시
for i in range(4):
    for j in range(3):
        print(b[i][j].data_ptr())

120522112
120522128
120522144
120522116
120522132
120522148
120522120
120522136
120522152
120522124
120522140
120522156
120522368
120522372
120522376
120522380
120522384
120522388
120522392
120522396
120522400
120522404
120522408
120522412
