In [1]:
import torch
x = torch.rand(5, 3)
x

tensor([[0.8689, 0.6829, 0.7118],
        [0.8088, 0.5369, 0.1495],
        [0.9646, 0.5452, 0.5491],
        [0.2982, 0.2708, 0.4471],
        [0.8180, 0.0083, 0.0411]])

In [2]:
x = torch.tensor([[0,1,1,2], [2,2,3,1]])
x

tensor([[0, 1, 1, 2],
        [2, 2, 3, 1]])

In [5]:
x = torch.rand(5, 3)
print(x)
print(torch.norm(x)) # default 값은 모두 제곱해서 더한 다음 루트
print(torch.norm(x, dim=0))

print(x)

norm_of_x = torch.norm(x, dim=1, keepdim= True) # 행에 대해서 정규화한 후

print(norm_of_x)

normalized_x = x.div(norm_of_x) # 행에 대해서 따로 나누었다.
print(normalized_x)
print(torch.sum(normalized_x)) # 모두 더한다.

tensor([[0.5331, 0.9286, 0.8381],
        [0.9742, 0.8738, 0.1786],
        [0.2350, 0.4857, 0.8268],
        [0.9462, 0.5753, 0.9402],
        [0.3790, 0.2988, 0.3610]])
tensor(2.6536)
tensor([1.5256, 1.5106, 1.5596])
tensor([[0.5331, 0.9286, 0.8381],
        [0.9742, 0.8738, 0.1786],
        [0.2350, 0.4857, 0.8268],
        [0.9462, 0.5753, 0.9402],
        [0.3790, 0.2988, 0.3610]])
tensor([[1.3598],
        [1.3207],
        [0.9873],
        [1.4526],
        [0.6027]])
tensor([[0.3920, 0.6829, 0.6164],
        [0.7376, 0.6616, 0.1352],
        [0.2380, 0.4920, 0.8374],
        [0.6514, 0.3960, 0.6472],
        [0.6288, 0.4958, 0.5990]])
tensor(8.2113)
